# Generated by Django 2.2.7 on 2021-05-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('spo2', models.IntegerField(default=None)),
                ('pulse', models.IntegerField(default=None)),
            ],
        ),
    ]
